name: AppleOps
options:
  bundleIdPrefix: com.yiyeshi0
  deploymentTarget:
    iOS: "17.0"
targets:
  AppleOps:
    type: application
    platform: iOS
    sources:
      - AppleOps
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.roooot.mond.26C862CCQV
        PRODUCT_NAME: AppleOps
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: AppleOps/Info.plist
        CODE_SIGN_ENTITLEMENTS: AppleOps/AppleOps.entitlements
        TARGETED_DEVICE_FAMILY: "1"
